// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/biblioteca.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define as mensagens
type Livro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Autor         string                 `protobuf:"bytes,3,opt,name=autor,proto3" json:"autor,omitempty"`
	Ano           int32                  `protobuf:"varint,4,opt,name=ano,proto3" json:"ano,omitempty"`
	Disponivel    bool                   `protobuf:"varint,5,opt,name=disponivel,proto3" json:"disponivel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Livro) Reset() {
	*x = Livro{}
	mi := &file_proto_biblioteca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Livro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Livro) ProtoMessage() {}

func (x *Livro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biblioteca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Livro.ProtoReflect.Descriptor instead.
func (*Livro) Descriptor() ([]byte, []int) {
	return file_proto_biblioteca_proto_rawDescGZIP(), []int{0}
}

func (x *Livro) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Livro) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Livro) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *Livro) GetAno() int32 {
	if x != nil {
		return x.Ano
	}
	return 0
}

func (x *Livro) GetDisponivel() bool {
	if x != nil {
		return x.Disponivel
	}
	return false
}

type ListaLivrosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Livros        []*Livro               `protobuf:"bytes,1,rep,name=livros,proto3" json:"livros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaLivrosResponse) Reset() {
	*x = ListaLivrosResponse{}
	mi := &file_proto_biblioteca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaLivrosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaLivrosResponse) ProtoMessage() {}

func (x *ListaLivrosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biblioteca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaLivrosResponse.ProtoReflect.Descriptor instead.
func (*ListaLivrosResponse) Descriptor() ([]byte, []int) {
	return file_proto_biblioteca_proto_rawDescGZIP(), []int{1}
}

func (x *ListaLivrosResponse) GetLivros() []*Livro {
	if x != nil {
		return x.Livros
	}
	return nil
}

type CriarLivroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Autor         string                 `protobuf:"bytes,2,opt,name=autor,proto3" json:"autor,omitempty"`
	Ano           int32                  `protobuf:"varint,3,opt,name=ano,proto3" json:"ano,omitempty"`
	Disponivel    bool                   `protobuf:"varint,4,opt,name=disponivel,proto3" json:"disponivel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarLivroRequest) Reset() {
	*x = CriarLivroRequest{}
	mi := &file_proto_biblioteca_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarLivroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarLivroRequest) ProtoMessage() {}

func (x *CriarLivroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biblioteca_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarLivroRequest.ProtoReflect.Descriptor instead.
func (*CriarLivroRequest) Descriptor() ([]byte, []int) {
	return file_proto_biblioteca_proto_rawDescGZIP(), []int{2}
}

func (x *CriarLivroRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *CriarLivroRequest) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *CriarLivroRequest) GetAno() int32 {
	if x != nil {
		return x.Ano
	}
	return 0
}

func (x *CriarLivroRequest) GetDisponivel() bool {
	if x != nil {
		return x.Disponivel
	}
	return false
}

type CriarLivroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Livro         *Livro                 `protobuf:"bytes,1,opt,name=livro,proto3" json:"livro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarLivroResponse) Reset() {
	*x = CriarLivroResponse{}
	mi := &file_proto_biblioteca_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarLivroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarLivroResponse) ProtoMessage() {}

func (x *CriarLivroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biblioteca_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarLivroResponse.ProtoReflect.Descriptor instead.
func (*CriarLivroResponse) Descriptor() ([]byte, []int) {
	return file_proto_biblioteca_proto_rawDescGZIP(), []int{3}
}

func (x *CriarLivroResponse) GetLivro() *Livro {
	if x != nil {
		return x.Livro
	}
	return nil
}

type Emprestimo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LivroId       int32                  `protobuf:"varint,2,opt,name=livro_id,json=livroId,proto3" json:"livro_id,omitempty"`
	UsuarioId     int32                  `protobuf:"varint,3,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	DataInicio    string                 `protobuf:"bytes,4,opt,name=data_inicio,json=dataInicio,proto3" json:"data_inicio,omitempty"`
	DataFim       string                 `protobuf:"bytes,5,opt,name=data_fim,json=dataFim,proto3" json:"data_fim,omitempty"`
	Devolvido     bool                   `protobuf:"varint,6,opt,name=devolvido,proto3" json:"devolvido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emprestimo) Reset() {
	*x = Emprestimo{}
	mi := &file_proto_biblioteca_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emprestimo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emprestimo) ProtoMessage() {}

func (x *Emprestimo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biblioteca_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emprestimo.ProtoReflect.Descriptor instead.
func (*Emprestimo) Descriptor() ([]byte, []int) {
	return file_proto_biblioteca_proto_rawDescGZIP(), []int{4}
}

func (x *Emprestimo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Emprestimo) GetLivroId() int32 {
	if x != nil {
		return x.LivroId
	}
	return 0
}

func (x *Emprestimo) GetUsuarioId() int32 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

func (x *Emprestimo) GetDataInicio() string {
	if x != nil {
		return x.DataInicio
	}
	return ""
}

func (x *Emprestimo) GetDataFim() string {
	if x != nil {
		return x.DataFim
	}
	return ""
}

func (x *Emprestimo) GetDevolvido() bool {
	if x != nil {
		return x.Devolvido
	}
	return false
}

type CriarEmprestimoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LivroId       int32                  `protobuf:"varint,1,opt,name=livro_id,json=livroId,proto3" json:"livro_id,omitempty"`
	UsuarioId     int32                  `protobuf:"varint,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	DataInicio    string                 `protobuf:"bytes,3,opt,name=data_inicio,json=dataInicio,proto3" json:"data_inicio,omitempty"`
	DataFim       string                 `protobuf:"bytes,4,opt,name=data_fim,json=dataFim,proto3" json:"data_fim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarEmprestimoRequest) Reset() {
	*x = CriarEmprestimoRequest{}
	mi := &file_proto_biblioteca_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarEmprestimoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarEmprestimoRequest) ProtoMessage() {}

func (x *CriarEmprestimoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biblioteca_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarEmprestimoRequest.ProtoReflect.Descriptor instead.
func (*CriarEmprestimoRequest) Descriptor() ([]byte, []int) {
	return file_proto_biblioteca_proto_rawDescGZIP(), []int{5}
}

func (x *CriarEmprestimoRequest) GetLivroId() int32 {
	if x != nil {
		return x.LivroId
	}
	return 0
}

func (x *CriarEmprestimoRequest) GetUsuarioId() int32 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

func (x *CriarEmprestimoRequest) GetDataInicio() string {
	if x != nil {
		return x.DataInicio
	}
	return ""
}

func (x *CriarEmprestimoRequest) GetDataFim() string {
	if x != nil {
		return x.DataFim
	}
	return ""
}

type CriarEmprestimoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emprestimo    *Emprestimo            `protobuf:"bytes,1,opt,name=emprestimo,proto3" json:"emprestimo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriarEmprestimoResponse) Reset() {
	*x = CriarEmprestimoResponse{}
	mi := &file_proto_biblioteca_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriarEmprestimoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarEmprestimoResponse) ProtoMessage() {}

func (x *CriarEmprestimoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_biblioteca_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarEmprestimoResponse.ProtoReflect.Descriptor instead.
func (*CriarEmprestimoResponse) Descriptor() ([]byte, []int) {
	return file_proto_biblioteca_proto_rawDescGZIP(), []int{6}
}

func (x *CriarEmprestimoResponse) GetEmprestimo() *Emprestimo {
	if x != nil {
		return x.Emprestimo
	}
	return nil
}

var File_proto_biblioteca_proto protoreflect.FileDescriptor

const file_proto_biblioteca_proto_rawDesc = "" +
	"\n" +
	"\x16proto/biblioteca.proto\x12\n" +
	"biblioteca\x1a\x1bgoogle/protobuf/empty.proto\"w\n" +
	"\x05Livro\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x14\n" +
	"\x05autor\x18\x03 \x01(\tR\x05autor\x12\x10\n" +
	"\x03ano\x18\x04 \x01(\x05R\x03ano\x12\x1e\n" +
	"\n" +
	"disponivel\x18\x05 \x01(\bR\n" +
	"disponivel\"@\n" +
	"\x13ListaLivrosResponse\x12)\n" +
	"\x06livros\x18\x01 \x03(\v2\x11.biblioteca.LivroR\x06livros\"s\n" +
	"\x11CriarLivroRequest\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\x12\x14\n" +
	"\x05autor\x18\x02 \x01(\tR\x05autor\x12\x10\n" +
	"\x03ano\x18\x03 \x01(\x05R\x03ano\x12\x1e\n" +
	"\n" +
	"disponivel\x18\x04 \x01(\bR\n" +
	"disponivel\"=\n" +
	"\x12CriarLivroResponse\x12'\n" +
	"\x05livro\x18\x01 \x01(\v2\x11.biblioteca.LivroR\x05livro\"\xb0\x01\n" +
	"\n" +
	"Emprestimo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\blivro_id\x18\x02 \x01(\x05R\alivroId\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x03 \x01(\x05R\tusuarioId\x12\x1f\n" +
	"\vdata_inicio\x18\x04 \x01(\tR\n" +
	"dataInicio\x12\x19\n" +
	"\bdata_fim\x18\x05 \x01(\tR\adataFim\x12\x1c\n" +
	"\tdevolvido\x18\x06 \x01(\bR\tdevolvido\"\x8e\x01\n" +
	"\x16CriarEmprestimoRequest\x12\x19\n" +
	"\blivro_id\x18\x01 \x01(\x05R\alivroId\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\x05R\tusuarioId\x12\x1f\n" +
	"\vdata_inicio\x18\x03 \x01(\tR\n" +
	"dataInicio\x12\x19\n" +
	"\bdata_fim\x18\x04 \x01(\tR\adataFim\"Q\n" +
	"\x17CriarEmprestimoResponse\x126\n" +
	"\n" +
	"emprestimo\x18\x01 \x01(\v2\x16.biblioteca.EmprestimoR\n" +
	"emprestimo2\x85\x02\n" +
	"\x11BibliotecaService\x12G\n" +
	"\fListarLivros\x12\x16.google.protobuf.Empty\x1a\x1f.biblioteca.ListaLivrosResponse\x12K\n" +
	"\n" +
	"CriarLivro\x12\x1d.biblioteca.CriarLivroRequest\x1a\x1e.biblioteca.CriarLivroResponse\x12Z\n" +
	"\x0fCriarEmprestimo\x12\".biblioteca.CriarEmprestimoRequest\x1a#.biblioteca.CriarEmprestimoResponseB%Z#github.com/llopes05/RESTeSOAP/protob\x06proto3"

var (
	file_proto_biblioteca_proto_rawDescOnce sync.Once
	file_proto_biblioteca_proto_rawDescData []byte
)

func file_proto_biblioteca_proto_rawDescGZIP() []byte {
	file_proto_biblioteca_proto_rawDescOnce.Do(func() {
		file_proto_biblioteca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_biblioteca_proto_rawDesc), len(file_proto_biblioteca_proto_rawDesc)))
	})
	return file_proto_biblioteca_proto_rawDescData
}

var file_proto_biblioteca_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_biblioteca_proto_goTypes = []any{
	(*Livro)(nil),                   // 0: biblioteca.Livro
	(*ListaLivrosResponse)(nil),     // 1: biblioteca.ListaLivrosResponse
	(*CriarLivroRequest)(nil),       // 2: biblioteca.CriarLivroRequest
	(*CriarLivroResponse)(nil),      // 3: biblioteca.CriarLivroResponse
	(*Emprestimo)(nil),              // 4: biblioteca.Emprestimo
	(*CriarEmprestimoRequest)(nil),  // 5: biblioteca.CriarEmprestimoRequest
	(*CriarEmprestimoResponse)(nil), // 6: biblioteca.CriarEmprestimoResponse
	(*emptypb.Empty)(nil),           // 7: google.protobuf.Empty
}
var file_proto_biblioteca_proto_depIdxs = []int32{
	0, // 0: biblioteca.ListaLivrosResponse.livros:type_name -> biblioteca.Livro
	0, // 1: biblioteca.CriarLivroResponse.livro:type_name -> biblioteca.Livro
	4, // 2: biblioteca.CriarEmprestimoResponse.emprestimo:type_name -> biblioteca.Emprestimo
	7, // 3: biblioteca.BibliotecaService.ListarLivros:input_type -> google.protobuf.Empty
	2, // 4: biblioteca.BibliotecaService.CriarLivro:input_type -> biblioteca.CriarLivroRequest
	5, // 5: biblioteca.BibliotecaService.CriarEmprestimo:input_type -> biblioteca.CriarEmprestimoRequest
	1, // 6: biblioteca.BibliotecaService.ListarLivros:output_type -> biblioteca.ListaLivrosResponse
	3, // 7: biblioteca.BibliotecaService.CriarLivro:output_type -> biblioteca.CriarLivroResponse
	6, // 8: biblioteca.BibliotecaService.CriarEmprestimo:output_type -> biblioteca.CriarEmprestimoResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_biblioteca_proto_init() }
func file_proto_biblioteca_proto_init() {
	if File_proto_biblioteca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_biblioteca_proto_rawDesc), len(file_proto_biblioteca_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_biblioteca_proto_goTypes,
		DependencyIndexes: file_proto_biblioteca_proto_depIdxs,
		MessageInfos:      file_proto_biblioteca_proto_msgTypes,
	}.Build()
	File_proto_biblioteca_proto = out.File
	file_proto_biblioteca_proto_goTypes = nil
	file_proto_biblioteca_proto_depIdxs = nil
}
