syntax = "proto3";

package biblioteca;

import "google/protobuf/empty.proto"; // Mova o import para o topo

option go_package = "github.com/llopes05/RESTeSOAP/proto";

// --- Mensagens ---
message Livro {
  int32 id = 1;
  string titulo = 2;
  string autor = 3;
  int32 ano = 4;
  bool disponivel = 5;
}

message ListaLivrosResponse {
  repeated Livro livros = 1;
}

message CriarLivroRequest {
  string titulo = 1;
  string autor = 2;
  int32 ano = 3;
  bool disponivel = 4;
}

message CriarLivroResponse {
  Livro livro = 1;
}

message Emprestimo {
  int32 id = 1;
  int32 livro_id = 2;
  int32 usuario_id = 3;
  string data_inicio = 4;
  string data_fim = 5;
  bool devolvido = 6;
}

message CriarEmprestimoRequest {
  int32 livro_id = 1;
  int32 usuario_id = 2;
  string data_inicio = 3;
  string data_fim = 4;
}

message CriarEmprestimoResponse {
  Emprestimo emprestimo = 1;
}

// MENSAGEM FALTANTE
message DeletarLivroRequest {
  int32 id = 1;
}


// --- Serviço da biblioteca ---
service BibliotecaService {
  rpc ListarLivros (google.protobuf.Empty) returns (ListaLivrosResponse);
  rpc CriarLivro (CriarLivroRequest) returns (CriarLivroResponse);
  rpc CriarEmprestimo (CriarEmprestimoRequest) returns (CriarEmprestimoResponse);

  // RPC FALTANTE
  rpc DeletarLivro (DeletarLivroRequest) returns (google.protobuf.Empty);
}