// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/biblioteca.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BibliotecaService_ListarLivros_FullMethodName    = "/biblioteca.BibliotecaService/ListarLivros"
	BibliotecaService_CriarLivro_FullMethodName      = "/biblioteca.BibliotecaService/CriarLivro"
	BibliotecaService_CriarEmprestimo_FullMethodName = "/biblioteca.BibliotecaService/CriarEmprestimo"
	BibliotecaService_DeletarLivro_FullMethodName    = "/biblioteca.BibliotecaService/DeletarLivro"
)

// BibliotecaServiceClient is the client API for BibliotecaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- Serviço da biblioteca ---
type BibliotecaServiceClient interface {
	ListarLivros(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListaLivrosResponse, error)
	CriarLivro(ctx context.Context, in *CriarLivroRequest, opts ...grpc.CallOption) (*CriarLivroResponse, error)
	CriarEmprestimo(ctx context.Context, in *CriarEmprestimoRequest, opts ...grpc.CallOption) (*CriarEmprestimoResponse, error)
	// RPC FALTANTE
	DeletarLivro(ctx context.Context, in *DeletarLivroRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type bibliotecaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBibliotecaServiceClient(cc grpc.ClientConnInterface) BibliotecaServiceClient {
	return &bibliotecaServiceClient{cc}
}

func (c *bibliotecaServiceClient) ListarLivros(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListaLivrosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaLivrosResponse)
	err := c.cc.Invoke(ctx, BibliotecaService_ListarLivros_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bibliotecaServiceClient) CriarLivro(ctx context.Context, in *CriarLivroRequest, opts ...grpc.CallOption) (*CriarLivroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CriarLivroResponse)
	err := c.cc.Invoke(ctx, BibliotecaService_CriarLivro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bibliotecaServiceClient) CriarEmprestimo(ctx context.Context, in *CriarEmprestimoRequest, opts ...grpc.CallOption) (*CriarEmprestimoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CriarEmprestimoResponse)
	err := c.cc.Invoke(ctx, BibliotecaService_CriarEmprestimo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bibliotecaServiceClient) DeletarLivro(ctx context.Context, in *DeletarLivroRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BibliotecaService_DeletarLivro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BibliotecaServiceServer is the server API for BibliotecaService service.
// All implementations must embed UnimplementedBibliotecaServiceServer
// for forward compatibility.
//
// --- Serviço da biblioteca ---
type BibliotecaServiceServer interface {
	ListarLivros(context.Context, *emptypb.Empty) (*ListaLivrosResponse, error)
	CriarLivro(context.Context, *CriarLivroRequest) (*CriarLivroResponse, error)
	CriarEmprestimo(context.Context, *CriarEmprestimoRequest) (*CriarEmprestimoResponse, error)
	// RPC FALTANTE
	DeletarLivro(context.Context, *DeletarLivroRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBibliotecaServiceServer()
}

// UnimplementedBibliotecaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBibliotecaServiceServer struct{}

func (UnimplementedBibliotecaServiceServer) ListarLivros(context.Context, *emptypb.Empty) (*ListaLivrosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListarLivros not implemented")
}
func (UnimplementedBibliotecaServiceServer) CriarLivro(context.Context, *CriarLivroRequest) (*CriarLivroResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarLivro not implemented")
}
func (UnimplementedBibliotecaServiceServer) CriarEmprestimo(context.Context, *CriarEmprestimoRequest) (*CriarEmprestimoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarEmprestimo not implemented")
}
func (UnimplementedBibliotecaServiceServer) DeletarLivro(context.Context, *DeletarLivroRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletarLivro not implemented")
}
func (UnimplementedBibliotecaServiceServer) mustEmbedUnimplementedBibliotecaServiceServer() {}
func (UnimplementedBibliotecaServiceServer) testEmbeddedByValue()                           {}

// UnsafeBibliotecaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BibliotecaServiceServer will
// result in compilation errors.
type UnsafeBibliotecaServiceServer interface {
	mustEmbedUnimplementedBibliotecaServiceServer()
}

func RegisterBibliotecaServiceServer(s grpc.ServiceRegistrar, srv BibliotecaServiceServer) {
	// If the following call pancis, it indicates UnimplementedBibliotecaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BibliotecaService_ServiceDesc, srv)
}

func _BibliotecaService_ListarLivros_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BibliotecaServiceServer).ListarLivros(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BibliotecaService_ListarLivros_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BibliotecaServiceServer).ListarLivros(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BibliotecaService_CriarLivro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarLivroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BibliotecaServiceServer).CriarLivro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BibliotecaService_CriarLivro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BibliotecaServiceServer).CriarLivro(ctx, req.(*CriarLivroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BibliotecaService_CriarEmprestimo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarEmprestimoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BibliotecaServiceServer).CriarEmprestimo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BibliotecaService_CriarEmprestimo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BibliotecaServiceServer).CriarEmprestimo(ctx, req.(*CriarEmprestimoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BibliotecaService_DeletarLivro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletarLivroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BibliotecaServiceServer).DeletarLivro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BibliotecaService_DeletarLivro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BibliotecaServiceServer).DeletarLivro(ctx, req.(*DeletarLivroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BibliotecaService_ServiceDesc is the grpc.ServiceDesc for BibliotecaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BibliotecaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "biblioteca.BibliotecaService",
	HandlerType: (*BibliotecaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListarLivros",
			Handler:    _BibliotecaService_ListarLivros_Handler,
		},
		{
			MethodName: "CriarLivro",
			Handler:    _BibliotecaService_CriarLivro_Handler,
		},
		{
			MethodName: "CriarEmprestimo",
			Handler:    _BibliotecaService_CriarEmprestimo_Handler,
		},
		{
			MethodName: "DeletarLivro",
			Handler:    _BibliotecaService_DeletarLivro_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/biblioteca.proto",
}
