// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/emprestimos": {
            "post": {
                "description": "Registra um novo empréstimo de livro",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "emprestimos"
                ],
                "summary": "Criar um novo empréstimo",
                "parameters": [
                    {
                        "description": "Dados do empréstimo",
                        "name": "emprestimo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Emprestimo"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Emprestimo"
                        }
                    }
                }
            }
        },
        "/livros": {
            "post": {
                "description": "Adiciona um novo livro à biblioteca",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "livros"
                ],
                "summary": "Criar um novo livro",
                "parameters": [
                    {
                        "description": "Dados do livro",
                        "name": "livro",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Livro"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Livro"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Emprestimo": {
            "type": "object"
        },
        "models.Livro": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
